### ISSUE TITLE
How to execute

### ISSUE THREAD

**Issue by beanbag247** [Unknown-Kush/OpenCryptShot#4]
Hello, how do you execute this program?

I opened it in microsoft visuals. In the download folder I cannot find a json file but a config.cs instead.
So in notepad I changed the settings and inserted the key, but how to get to the part where I put in the coinname and start the transaction?
Thanks for your help.

**Comment by Unknown-Kush** [comment]
I suggest you download a release. There is no need to use visual studio if you're not familiar with it.
https://github.com/Unknown-Kush/OpenCryptShot/releases/
